{{- if .Values.sqlServer.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "nginx-configurable-index.fullname" . }}-sqlserver
  labels:
    app: {{ template "nginx-configurable-index.name" . }}
    chart: {{ template "nginx-configurable-index.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nginx-configurable-index.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nginx-configurable-index.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "microsoft/mssql-server-linux:{{ .Values.sqlServer.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: {{ default "yourStrong(!)Password" .Values.sqlServer.password }}
          ports:
            - name: sql
              containerPort: 1433
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: sql
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: sql
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
